name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # or master, depending on your default branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/rotzrohr/utopiamc-docs:latest
          cache-from: type=registry,ref=ghcr.io/rotzrohr/utopiamc-docs:buildcache
          cache-to: type=registry,ref=ghcr.io/rotzrohr/utopiamc-docs:buildcache,mode=max